# Placeholder word list. Each card is (category, [(word, romaji, meaning), ...6]).
# The category is only for organizing this file. It is never sent to players.

CARDS = [
    ("food", [
        ("パン", "pan", "Bread"),
        ("バナナ", "banana", "Banana: a long yellow fruit"),
        ("トマト", "tomato", "Tomato"),
        ("チョコレート", "chokorēto", "Chocolate"),
        ("ハンバーガー", "hanbāgā", "Hamburger"),
        ("サンドイッチ", "sandoicchi", "Sandwich"),
    ]),
    ("drinks", [
        ("コーヒー", "kōhī", "Coffee: a dark, bitter morning drink"),
        ("ジュース", "jūsu", "Juice"),
        ("ビール", "bīru", "Beer"),
        ("コーラ", "kōra", "Cola"),
        ("ミルク", "miruku", "Milk"),
        ("ワイン", "wain", "Wine"),
    ]),
    ("around the house", [
        ("テレビ", "terebi", "Television"),
        ("ベッド", "beddo", "Bed"),
        ("ドア", "doa", "Door"),
        ("シャワー", "shawā", "Shower"),
        ("カレンダー", "karendā", "Calendar"),
        ("スプーン", "supūn", "Spoon"),
    ]),
    ("getting around", [
        ("タクシー", "takushī", "Taxi: a car you pay to ride in"),
        ("バス", "basu", "Bus"),
        ("エレベーター", "erebētā", "Elevator: a box that carries you between floors"),
        ("ヘリコプター", "herikoputā", "Helicopter"),
        ("バイク", "baiku", "Motorcycle (not a bicycle!)"),
        ("トラック", "torakku", "Truck"),
    ]),
    ("hobbies", [
        ("ギター", "gitā", "Guitar"),
        ("ピアノ", "piano", "Piano"),
        ("カラオケ", "karaoke", "Karaoke: singing along to music"),
        ("キャンプ", "kyanpu", "Camping"),
        ("マラソン", "marason", "Marathon: a very long running race"),
        ("サッカー", "sakkā", "Soccer (football)"),
    ]),
    ("gadgets", [
        ("パソコン", "pasokon", "Personal computer (PC)"),
        ("スマホ", "sumaho", "Smartphone"),
        ("カメラ", "kamera", "Camera"),
        ("ラジオ", "rajio", "Radio"),
        ("ロボット", "robotto", "Robot"),
        ("ドライヤー", "doraiyā", "Hair dryer: blows hot air to dry hair"),
    ]),
    ("animals", [
        ("ペンギン", "pengin", "Penguin: a bird that swims but can't fly"),
        ("ライオン", "raion", "Lion"),
        ("パンダ", "panda", "Panda"),
        ("ゴリラ", "gorira", "Gorilla"),
        ("キリン", "kirin", "Giraffe"),
        ("コアラ", "koara", "Koala"),
    ]),
    ("office supplies", [
        ("ホッチキス", "hocchikisu", "Stapler (named after a brand)"),
        ("クリップ", "kurippu", "Paper clip"),
        ("ボールペン", "bōrupen", "Ballpoint pen"),
        ("ファイル", "fairu", "Folder for papers"),
        ("セロテープ", "serotēpu", "Clear sticky tape"),
        ("カッター", "kattā", "Box cutter, utility knife"),
    ]),
    ("clothes", [
        ("シャツ", "shatsu", "Shirt"),
        ("ズボン", "zubon", "Pants, trousers"),
        ("スカート", "sukāto", "Skirt"),
        ("ネクタイ", "nekutai", "Necktie"),
        ("セーター", "sētā", "Sweater"),
        ("ジーンズ", "jīnzu", "Jeans"),
    ]),
    ("sports", [
        ("テニス", "tenisu", "Tennis"),
        ("ゴルフ", "gorufu", "Golf"),
        ("スキー", "sukī", "Skiing"),
        ("ボクシング", "bokushingu", "Boxing"),
        ("バスケットボール", "basukettobōru", "Basketball"),
        ("ボウリング", "bōringu", "Bowling"),
    ]),
    ("kitchen", [
        ("フライパン", "furaipan", "Frying pan"),
        ("ナイフ", "naifu", "Knife"),
        ("フォーク", "fōku", "Fork"),
        ("コップ", "koppu", "Drinking glass, cup"),
        ("オーブン", "ōbun", "Oven"),
        ("ミキサー", "mikisā", "Blender (not a stand mixer)"),
    ]),
    ("sweets", [
        ("ケーキ", "kēki", "Cake"),
        ("アイスクリーム", "aisukurīmu", "Ice cream"),
        ("クッキー", "kukkī", "Cookie"),
        ("プリン", "purin", "Custard pudding with caramel on top"),
        ("ドーナツ", "dōnatsu", "Donut"),
        ("キャンディー", "kyandī", "Candy"),
    ]),
    ("around town", [
        ("ホテル", "hoteru", "Hotel"),
        ("デパート", "depāto", "Department store"),
        ("コンビニ", "konbini", "Convenience store"),
        ("レストラン", "resutoran", "Restaurant"),
        ("スーパー", "sūpā", "Supermarket"),
        ("ビル", "biru", "Tall building, like an office tower"),
    ]),
    ("jobs", [
        ("パイロット", "pairotto", "Pilot"),
        ("コック", "kokku", "Cook, chef"),
        ("ナース", "nāsu", "Nurse"),
        ("デザイナー", "dezainā", "Designer"),
        ("エンジニア", "enjinia", "Engineer"),
        ("アナウンサー", "anaunsā", "TV news presenter"),
    ]),
    ("music", [
        ("ドラム", "doramu", "Drums"),
        ("バイオリン", "baiorin", "Violin"),
        ("トランペット", "toranpetto", "Trumpet"),
        ("コンサート", "konsāto", "Concert"),
        ("マイク", "maiku", "Microphone"),
        ("メロディー", "merodī", "Melody, tune"),
    ]),
    ("fruit", [
        ("メロン", "meron", "Melon"),
        ("レモン", "remon", "Lemon"),
        ("オレンジ", "orenji", "Orange"),
        ("キウイ", "kiui", "Kiwi fruit"),
        ("マンゴー", "mangō", "Mango"),
        ("パイナップル", "painappuru", "Pineapple"),
    ]),
    ("vegetables", [
        ("キャベツ", "kyabetsu", "Cabbage"),
        ("レタス", "retasu", "Lettuce"),
        ("ピーマン", "pīman", "Green bell pepper"),
        ("ブロッコリー", "burokkorī", "Broccoli"),
        ("セロリ", "serori", "Celery"),
        ("アスパラガス", "asuparagasu", "Asparagus"),
    ]),
    ("bathroom", [
        ("シャンプー", "shanpū", "Shampoo"),
        ("トイレ", "toire", "Toilet, restroom"),
        ("タオル", "taoru", "Towel"),
        ("ティッシュ", "tisshu", "Tissues"),
        ("ボディソープ", "bodisōpu", "Body wash"),
        ("リンス", "rinsu", "Hair conditioner"),
    ]),
    ("school", [
        ("テスト", "tesuto", "Test, exam"),
        ("ノート", "nōto", "Notebook"),
        ("クラス", "kurasu", "Class"),
        ("チャイム", "chaimu", "The bell that rings between classes"),
        ("プール", "pūru", "Swimming pool"),
        ("ランドセル", "randoseru", "Stiff leather backpack for elementary school"),
    ]),
    ("holidays", [
        ("クリスマス", "kurisumasu", "Christmas"),
        ("プレゼント", "purezento", "Present, gift"),
        ("パーティー", "pātī", "Party"),
        ("バレンタイン", "barentain", "Valentine's Day"),
        ("ハロウィン", "harowin", "Halloween"),
        ("カウントダウン", "kauntodaun", "Countdown, like on New Year's Eve"),
    ]),
    ("internet", [
        ("メール", "mēru", "Email"),
        ("パスワード", "pasuwādo", "Password"),
        ("インターネット", "intānetto", "The internet"),
        ("アプリ", "apuri", "App"),
        ("ゲーム", "gēmu", "Video game"),
        ("ダウンロード", "daunrōdo", "Download"),
    ]),
    ("furniture", [
        ("ソファー", "sofā", "Sofa, couch"),
        ("テーブル", "tēburu", "Table"),
        ("カーテン", "kāten", "Curtains"),
        ("ランプ", "ranpu", "Lamp"),
        ("カーペット", "kāpetto", "Carpet, rug"),
        ("エアコン", "eakon", "Air conditioner"),
    ]),
    ("travel", [
        ("パスポート", "pasupōto", "Passport"),
        ("スーツケース", "sūtsukēsu", "Suitcase"),
        ("チケット", "chiketto", "Ticket"),
        ("ガイド", "gaido", "Tour guide"),
        ("ツアー", "tsuā", "Tour, package trip"),
        ("ホームステイ", "hōmusutei", "Living with a local family while abroad"),
    ]),
    ("made-in-japan english", [
        ("サラリーマン", "sararīman", "Office worker on a salary"),
        ("マンション", "manshon", "Apartment building (not a mansion!)"),
        ("ペーパードライバー", "pēpādoraibā", "Someone with a license who never drives"),
        ("バイキング", "baikingu", "All-you-can-eat buffet"),
        ("コンセント", "konsento", "Wall power outlet"),
        ("シャープペンシル", "shāpupenshiru", "Mechanical pencil"),
    ]),
    ("flavors", [
        ("ケチャップ", "kechappu", "Ketchup"),
        ("マヨネーズ", "mayonēzu", "Mayonnaise"),
        ("ソース", "sōsu", "Thick, sweet brown sauce for fried food"),
        ("バター", "batā", "Butter"),
        ("カレー", "karē", "Curry"),
        ("ドレッシング", "doresshingu", "Salad dressing"),
    ]),
    ("health", [
        ("ダイエット", "daietto", "Going on a diet to lose weight"),
        ("ストレス", "sutoresu", "Stress"),
        ("マッサージ", "massāji", "Massage"),
        ("ビタミン", "bitamin", "Vitamin"),
        ("アレルギー", "arerugī", "Allergy"),
        ("リハビリ", "rihabiri", "Physical therapy after an injury"),
    ]),
    ("toys", [
        ("パズル", "pazuru", "Puzzle"),
        ("トランプ", "toranpu", "Deck of playing cards"),
        ("ボール", "bōru", "Ball"),
        ("ブランコ", "buranko", "Playground swing"),
        ("ジャングルジム", "janguru jimu", "Jungle gym, climbing frame"),
        ("ヨーヨー", "yōyō", "Yo-yo"),
    ]),
    ("tv and movies", [
        ("アニメ", "anime", "Animated show or movie"),
        ("ドラマ", "dorama", "TV drama series"),
        ("ニュース", "nyūsu", "The news"),
        ("コマーシャル", "komāsharu", "TV commercial, ad"),
        ("ヒーロー", "hīrō", "Hero"),
        ("ホラー", "horā", "Horror"),
    ]),
    ("cars", [
        ("ハンドル", "handoru", "Steering wheel (not a door handle!)"),
        ("ブレーキ", "burēki", "Brakes"),
        ("アクセル", "akuseru", "Gas pedal"),
        ("タイヤ", "taiya", "Tire"),
        ("ガソリン", "gasorin", "Gasoline"),
        ("クラクション", "kurakushon", "Car horn"),
    ]),
    ("cafe", [
        ("メニュー", "menyū", "Menu"),
        ("レジ", "reji", "Checkout counter, cash register"),
        ("ウェイター", "weitā", "Waiter"),
        ("テイクアウト", "teikuauto", "Takeout, to go"),
        ("サービス", "sābisu", "Something extra for free, on the house"),
        ("チップ", "chippu", "Tip for good service"),
    ]),
]
